[package]
name = "s6_hcs_lib_crypto"
version = "0.2.1"
edition = "2021"


[dependencies]
rand = "0.8.5"
num-bigint = { version = "0.4.4", features = ["rand", "serde"] }
num-traits = "0.2.17"
num-integer = "0.1.45"
log = "0.4.20"
maplit = "1.0.2"
serde = { version = "1.0", features = ["derive"] }
